
IMG_DIM = 96
MAX_PIXEL_VAL = 255.0
MAX_FEATURE = 30
MAX_TRAIN_IMG = 7049
MAX_TEST_IMG = 1073


FILEPATH_DATA_DIR = "../data/"
FILEPATH_TRAIN = FILEPATH_DATA_DIR.."training.csv"
FILEPATH_TEST = FILEPATH_DATA_DIR.."test.csv"
FILEPATH_TEST_FEATURE = FILEPATH_DATA_DIR.."test.csv"
